version: '3'
services:
  java-back:
    build:
      context: .
      dockerfile: /Dockerfile
    networks:
      - back-tier
    volumes:
      - data:/app/data
    restart: always

  nginx-front:
    build:
      context: .
      dockerfile: /front/Dockerfile
    depends_on:
      - java-back
    restart: always
    networks:
      - back-tier

volumes:
  data:
networks:
  back-tier:
    driver: bridge