version: '3'
services:
  java-back:
    build:
      dockerfile: /back/Dockerfile
    expose:
      - "80"
    ports:
      - "8080:80"
    networks:
      - back-tier
  nginx-front:
    build:
      dockerfile: /front/Dockerfile
    depends_on:
      - java-back
    links:
      - java-back
    ports:
      - "80:80"
    networks:
      - back-tier
networks:
  front-tier:
  back-tier: